// flow-typed signature: 67add3d538bab8dfbb19b831a8d41d2e
// flow-typed version: <<STUB>>/draft-js-code_v^0.2.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-code'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-code' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-code/demo/main' {
  declare module.exports: any;
}

declare module 'draft-js-code/lib/__tests__/getLineAnchorForOffset' {
  declare module.exports: any;
}

declare module 'draft-js-code/lib/getIndentation' {
  declare module.exports: any;
}

declare module 'draft-js-code/lib/getIndentForLine' {
  declare module.exports: any;
}

declare module 'draft-js-code/lib/getKeyBinding' {
  declare module.exports: any;
}

declare module 'draft-js-code/lib/getLineAnchorForOffset' {
  declare module.exports: any;
}

declare module 'draft-js-code/lib/getLines' {
  declare module.exports: any;
}

declare module 'draft-js-code/lib/getNewLine' {
  declare module.exports: any;
}

declare module 'draft-js-code/lib/handleKeyCommand' {
  declare module.exports: any;
}

declare module 'draft-js-code/lib/handleReturn' {
  declare module.exports: any;
}

declare module 'draft-js-code/lib/handleTab' {
  declare module.exports: any;
}

declare module 'draft-js-code/lib/hasSelectionInBlock' {
  declare module.exports: any;
}

declare module 'draft-js-code/lib/index' {
  declare module.exports: any;
}

declare module 'draft-js-code/lib/insertNewLine' {
  declare module.exports: any;
}

declare module 'draft-js-code/lib/removeIndent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-code/demo/main.js' {
  declare module.exports: $Exports<'draft-js-code/demo/main'>;
}
declare module 'draft-js-code/lib/__tests__/getLineAnchorForOffset.js' {
  declare module.exports: $Exports<'draft-js-code/lib/__tests__/getLineAnchorForOffset'>;
}
declare module 'draft-js-code/lib/getIndentation.js' {
  declare module.exports: $Exports<'draft-js-code/lib/getIndentation'>;
}
declare module 'draft-js-code/lib/getIndentForLine.js' {
  declare module.exports: $Exports<'draft-js-code/lib/getIndentForLine'>;
}
declare module 'draft-js-code/lib/getKeyBinding.js' {
  declare module.exports: $Exports<'draft-js-code/lib/getKeyBinding'>;
}
declare module 'draft-js-code/lib/getLineAnchorForOffset.js' {
  declare module.exports: $Exports<'draft-js-code/lib/getLineAnchorForOffset'>;
}
declare module 'draft-js-code/lib/getLines.js' {
  declare module.exports: $Exports<'draft-js-code/lib/getLines'>;
}
declare module 'draft-js-code/lib/getNewLine.js' {
  declare module.exports: $Exports<'draft-js-code/lib/getNewLine'>;
}
declare module 'draft-js-code/lib/handleKeyCommand.js' {
  declare module.exports: $Exports<'draft-js-code/lib/handleKeyCommand'>;
}
declare module 'draft-js-code/lib/handleReturn.js' {
  declare module.exports: $Exports<'draft-js-code/lib/handleReturn'>;
}
declare module 'draft-js-code/lib/handleTab.js' {
  declare module.exports: $Exports<'draft-js-code/lib/handleTab'>;
}
declare module 'draft-js-code/lib/hasSelectionInBlock.js' {
  declare module.exports: $Exports<'draft-js-code/lib/hasSelectionInBlock'>;
}
declare module 'draft-js-code/lib/index.js' {
  declare module.exports: $Exports<'draft-js-code/lib/index'>;
}
declare module 'draft-js-code/lib/insertNewLine.js' {
  declare module.exports: $Exports<'draft-js-code/lib/insertNewLine'>;
}
declare module 'draft-js-code/lib/removeIndent.js' {
  declare module.exports: $Exports<'draft-js-code/lib/removeIndent'>;
}
